### ISSUE TITLE
Problem with class attribute

### ISSUE THREAD

**Issue by jnotse** [TUHH-TVT/openCOSMO-RS_py#3]
Hello. I've been trying to use the `generate_conformers.py`, but an error arises at line 258, in the `_calculate_orca` method:

`orcacosmofile.save_xyz_file(filepath_xyz)
                xyz_files.append(filename + '.xyz')`

According to the traceback, `COSMOParser()` class doesn't have a `save_xyz_file` attribute, so the calculations stuck at the orca_am1 step. Im able to run the example `cosmors_calculation.ipynb` and get the same results, but Im facing this issue when trying new molecules. Any ideas would be much appreciated!

**Comment by simonmb** [comment]
Hola Joaquín, could you try taking the lat4est version of the repository? Because we are not using AM1 anymore and a file named generate_conformers.py actually does not exist anymore. You are working on an early version that is not the one we used in the paper. I am goint to close this issue as I tested a calculation on my computer and it ran fine. Please reopen if you still have problems after it. And please open new issues on the corresponding repo.
